services:
  revisium-core:
    pull_policy: always
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_started
    image: revisium/revisium-core:v1.0.0
    environment:
      DATABASE_URL: postgresql://revisium:password@db:5432/revisium-dev?schema=public
      ENDPOINT_PORT: 6379
      ENDPOINT_HOST: redis
      ADMIN_PASSWORD: 'password'
      ENDPOINT_PASSWORD: 'password'
      METRICS_ENABLED: 'true'
      GRACEFUL_SHUTDOWN_TIMEOUT: 10000
#      OAUTH_GOOGLE_CLIENT_ID: ""
#      OAUTH_GOOGLE_SECRET_ID: ""
#      OAUTH_GITHUB_CLIENT_ID: ""
#      OAUTH_GITHUB_SECRET_ID: ""
#      FILE_PLUGIN_PUBLIC_ENDPOINT: ""
#      S3_ENDPOINT: ""
#      S3_REGION: ""
#      S3_BUCKET: ""
#      S3_ACCESS_KEY_ID: ""
#      S3_SECRET_ACCESS_KEY: ""
    healthcheck:
      test:
        ['CMD-SHELL', 'curl -f http://localhost:8080/health/liveness || exit 1']
      interval: 5s
      timeout: 1s
      retries: 15

  revisium-endpoint:
    pull_policy: always
    depends_on:
      revisium-core:
        condition: service_healthy
    image: revisium/revisium-endpoint:v1.1.0
    ports:
      - 8081:8080
    environment:
      DATABASE_URL: postgresql://revisium:password@db:5432/revisium-dev?schema=public
      ENDPOINT_PORT: 6379
      CORE_API_URL: 'http://revisium-core:8080'
      CORE_API_URL_USERNAME: 'endpoint'
      CORE_API_URL_PASSWORD: 'password'
      ENDPOINT_HOST: redis
      METRICS_ENABLED: 'true'
      GRACEFUL_SHUTDOWN_TIMEOUT: 10000

  revisium-admin:
    pull_policy: always
    depends_on:
      revisium-core:
        condition: service_healthy
    image: revisium/revisium-admin:v1.0.0
    ports:
      - 8080:8080
    environment:
      REACT_APP_GRAPHQL_SERVER_URL: /graphql
      REACT_APP_SWAGGER_SERVER_URL: /api
      REACT_APP_GRAPHQL_SERVER_HOST: revisium-core
      REACT_APP_GRAPHQL_SERVER_PORT: 8080
      REACT_APP_ENDPOINT_HOST: localhost
      REACT_APP_ENDPOINT_PORT: 8081

  redis:
    container_name: revisium_redis_container-dev
    image: redis:7.4-alpine
    volumes:
      - revisium_redis_container-dev_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s
      retries: 5
  db:
    container_name: revisium_pg_container-dev
    image: postgres:17.4-alpine
    volumes:
      - revisium_pg_container-dev_data:/var/lib/postgresql/data
      - ./backup:/backup
    restart: always
    environment:
      POSTGRES_DB: revisium-dev
      POSTGRES_USER: revisium
      POSTGRES_PASSWORD: password

volumes:
  revisium_pg_container-dev_data:
  revisium_redis_container-dev_data: