services:
  db:
    image: postgres:15.4-alpine
    restart: always
    environment:
      POSTGRES_DB: revisium-dev
      POSTGRES_USER: revisium
      POSTGRES_PASSWORD: password
  revisium:
    pull_policy: always
    depends_on:
      - db
    image: revisium/revisium:master
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgresql://revisium:password@db:5432/revisium-dev?schema=public
      METRICS_ENABLED: "true"